apiVersion: batch/v1
kind: Job
metadata:
  name: patch-gpu-gc
  namespace: gpu-operator
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: patch-gpu-gc-sa
      restartPolicy: Never
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          kubectl patch deployment nvidia-gpu-operator-node-feature-discovery-gc -n gpu-operator --type json -p='[{"op": "add", "path": "/spec/template/spec/tolerations", "value": [{"key":"CriticalAddonsOnly","operator":"Equal","value":"true","effect":"NoSchedule"}]}]' || true
          kubectl delete pod -n gpu-operator -l role=gc --ignore-not-found