replicaCount: "1"

controllerManagerAddr: ":8080"        

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

nodeSelector:
  node.kubernetes.io/instance-type: t3.small

tolerations:
  - key: CriticalAddonsOnly
    operator: Equal
    value: "true"
    effect: NoSchedule

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack

logLevel: info
watchNamespace: ""
githubAPIURL: https://api.github.com

