githubConfigUrl: "https://github.com/ckc9014/training-job"
githubConfigSecret: "github-app-auth"

replicaCount: "1"
runnerScaleSetName: "gpu-runner-set"

minRunners: "0"
maxRunners: "5"

labels:
  - "gpu-runner"

template:
  spec:
    containers:
      - name: runner
        image: "ghcr.io/actions/actions-runner:latest"
    tolerations:
      - key: nvidia.com/gpu
        operator: Equal
        value: "true"
        effect: NoSchedule

# Toleration for the listener pod (runs on system nodes)
listenerTemplate:
  metadata:
    labels:
      app: arc-runner-listener
  spec:
    tolerations:
      - key: CriticalAddonsOnly
        operator: Equal
        value: "true"
        effect: NoSchedule

