githubConfigUrl: "https://github.com/ckc9014/training-job"
githubConfigSecret: "github-app-auth"
runnerScaleSetName: "gpu-runner-set"
labels: {}                                   # no top‑level labels needed
runnerPodLabels:
  gpu-runner: "true"                         # required for runs-on: gpu-runner
minRunners: "0"
maxRunners: "5"

listenerTemplate:
  spec:
    tolerations:
      - key: CriticalAddonsOnly
        operator: Equal
        value: "true"
        effect: NoSchedule
    containers:
      - name: listener
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi

template:
  spec:
    terminationGracePeriodSeconds: 120
    volumes:
      - name: work
        emptyDir: {}
    tolerations:
      - key: nvidia.com/gpu
        operator: Equal
        value: "true"
        effect: NoSchedule
      - key: CriticalAddonsOnly
        operator: Equal
        value: "true"
        effect: NoSchedule
    nodeSelector:
      node.kubernetes.io/instance-type: g4dn.xlarge
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: karpenter.sh/nodepool
                  operator: In
                  values:
                    - gpu-nodepool
    containers:
      - name: runner
        image: "ghcr.io/actions/actions-runner:latest"
        command: ["sleep", "infinity"]
        env:
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
        resources:
          limits:
            cpu: "2000m"
            memory: "16Gi"
            nvidia.com/gpu: "1"
          requests:
            cpu: "1000m"
            memory: "8Gi"
            nvidia.com/gpu: "1"

containerMode:
  type: kubernetes

controllerServiceAccount:
  namespace: "arc-systems"
  name: "arc-gha-rs-controller"