
githubConfigUrl: https://github.com/your-org   
configSecret:
  name: github-app-auth                 


runnerScaleSetName: gpu-runner-set


serviceAccount:
  name: arc-controller-sa


flags:
  excludeLabelPropagationPrefixes:
    - "argocd.argoproj.io/instance"
    - "app.kubernetes.io/component"
    - "app.kubernetes.io/instance"
    - "app.kubernetes.io/managed-by"
    - "app.kubernetes.io/name"
    - "app.kubernetes.io/part-of"
    - "app.kubernetes.io/version"