operator:
  defaultRuntime: containerd
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

driver:
  enabled: true
  # version: "550.144.03" # Optional: this is the default version for chart v26.3.1

toolkit:
  enabled: true

devicePlugin:
  enabled: true

dcgmExporter:
  enabled: true

serviceMonitor:
  enabled: true

migManager:
  enabled: false

nodeStatusExporter:
  enabled: true

tolerations:
  - key: "nvidia.com/gpu"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"