name: Terraform Dev

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action (apply or destroy)'
        required: true
        type: choice
        options:
          - apply
          - destroy

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I'm just a placeholder"