name: Terraform Plan (Reusable)

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      aws_role_arn:        
        required: true
        type: string
      aws-region:
       required: false
       type: string
       default: 'eu-west-1'
      tf-state-bucket:
        type: string
        required: true
      tf-state-key:
        type: string
        required: true

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform and AWS
        uses: ./.github/actions/setup-terraform-oidc
        with:
          aws-role-arn: ${{ inputs.aws_role_arn }}
          aws_region: ${{ inputs.aws-region }}
          working-directory: ${{ inputs.working_directory }}
          tf-state-bucket: ${{ inputs.tf-state-bucket }}
          tf-state-key:  ${{ inputs.tf-state-key }}
      - name: Terraform Plan
        working-directory: ${{ inputs.working_directory }}
        run:  |
          VAR_FILE="envs/dev.tfvars"
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            VAR_FILE="envs/prod.tfvars"
          fi
          terraform plan -var-file="$VAR_FILE" -out=tfplan
      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ inputs.working_directory }}/tfplan