name: Terraform Plan (Reusable)

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      aws-role-arn:
        required: true
        type: string
      aws-region:
        required: false
        type: string
        default: 'eu-west-1'
      tf-state-bucket:
        type: string
        required: true
      tf-state-key:
        type: string
        required: true
      environment:
        required: true
        type: string
      tf_state_bucket_var:   
        required: true
        type: string
      aws_region_var:       
        required: true
        type: string

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform and AWS
        uses: ./.github/actions/setup-terraform-oidc
        with:
          aws-role-arn: ${{ inputs.aws-role-arn }}
          aws-region: ${{ inputs.aws-region }}
          working-directory: ${{ inputs.working-directory }}
          tf-state-bucket: ${{ inputs.tf-state-bucket }}
          tf-state-key: ${{ inputs.tf-state-key }}

      - name: Terraform Plan
        working-directory: ${{ inputs.working-directory }}
        run: |
          terraform plan -out=tfplan \
          -var-file="envs/${{ inputs.environment }}.tfvars" \
          -var="environment=${{ inputs.environment }}" \
          -var="tf_state_bucket=${{ inputs.tf_state_bucket_var }}" \
          -var="aws_region=${{ inputs.aws_region_var }}"
      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ inputs.working-directory }}/tfplan