name: Terraform Apply (Reusable)

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      aws-role-arn:
        required: true
        type: string
      aws-region:
       required: false
       type: string
       default: 'eu-west-1'
      tf-state-bucket:
        type: string
        required: true
      tf-state-key:
        type: string
        required: true

jobs:
  apply:
    runs-on: ubuntu-latest
    # outputs:
    #   cluster_name: ${{ steps.get_cluster.outputs.cluster_name }}
    #   cluster_endpoint: ${{ steps.get_cluster.outputs.cluster_endpoint }}
    steps:
      - name: Setup Terraform and AWS
        uses: ./.github/actions/setup-terraform-oidc
        with:
          aws-role-arn: ${{ inputs.aws-role-arn }}
          aws_region: ${{ inputs.aws-region }}
          working-directory: ${{ inputs.working-directory }}
          tf-state-bucket: ${{ inputs.tf-state-bucket }}
          tf-state-key: ${{ inputs.tf-state-key }}
      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ${{ inputs.working-directory }}
      - name: Terraform Apply
        working-directory: ${{ inputs.working-directory }}
        run: terraform apply tfplan
        
      # - name: Get cluster name and endpoint from Terraform
      #   id: get_cluster
      #   working-directory: ${{ inputs.working_directory }}
      #   run: |
      #     echo "cluster_name=$(terraform output -raw cluster_name)" >> $GITHUB_OUTPUT
      #     echo "cluster_endpoint=$(terraform output -raw cluster_endpoint)" >> $GITHUB_OUTPUT